name: Python App CI  # The name shown in the GitHub Actions tab

on:
  push:
    branches:
      - main    # Production branch
      - test    # Testing/staging branch
      - dev     # Development branch

jobs:
  setup-and-test:  # Job name

    runs-on: ubuntu-latest  # Run this job on the latest Ubuntu virtual machine

    environment: ${{ github.ref_name }}  # Automatically match to 'main', 'test', or 'dev' environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pulls your repo's code into the workflow environment

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use Python 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Make sure pip is up to date
          pip install -r requirements.txt      # Install your project's dependencies

      - name: Run basic health check
        run: |
          echo "✅ Flask app installed successfully"  # Placeholder command for future tests